### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by Imtinmin** [vidar-team/hctf_frontend#5]
是只能linux下npm install吗
![image](https://user-images.githubusercontent.com/38977612/61996093-18a3a580-b0c3-11e9-9386-245792326433.png)

**Comment by Last-Order** [comment]
不是，这应该是npm的问题，请自己查下资料寻找解决方案。

**Comment by Imtinmin** [comment]
![image](https://user-images.githubusercontent.com/38977612/62096620-d2169c80-b2b6-11e9-9e48-bba4d77e5058.png)
